print("            ^   ")
print("           / \ ")
print("          / | \ ")
print("         /  |  \ ")
print("        /___|___\ ")

print("       |        |")
print("       |        |")
print("       |        |")
print("       |        |")
print("       |        |")
print("       |        |")
print("       |        |")
print("       |        |")
print("       |        |")

print("      /|````````|\  ")
print("     / |        | \ ")
print("    /  |        |  \ ")
print("   /   |        |   \ ")
print("  /    |        |    \ ")
print(" /_____|        |_____\ ")
print("        ⌄⌄⌄⌄⌄⌄⌄⌄  ")
